version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "yourusername"
    assignees:
      - "yourusername"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # Documentation site dependencies
  - package-ecosystem: "npm"
    directory: "/docs/website"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "yourusername"
    assignees:
      - "yourusername"
    commit-message:
      prefix: "docs-deps"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "yourusername"
    assignees:
      - "yourusername"
    commit-message:
      prefix: "ci"
