name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Help us understand what you'd like to see added to kserve-vllm-mini.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have checked the public roadmap
          required: true
        - label: This is not a duplicate of an existing request
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New vLLM feature support
        - Backend comparison enhancement
        - Profile system improvement
        - Documentation improvement
        - Analysis and reporting
        - CLI enhancement
        - Configuration validation
        - Performance optimization
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current pain point?
      placeholder: |
        Currently, users cannot easily...
        This makes it difficult to...
        Without this feature, we have to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution in detail
      placeholder: |
        I would like to see...
        The feature should work by...
        Users would interact with it by...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide concrete examples of how this feature would be used
      placeholder: |
        Example 1: ./bench.sh --new-feature ...
        Example 2: Profile configuration with...
        Example 3: Expected output showing...
      render: bash
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches or workarounds have you considered?
      placeholder: |
        Alternative 1: ...
        Alternative 2: ...
        Current workaround: ...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Critical - blocking my usage"
        - "High - significantly improves my workflow"
        - "Medium - nice to have improvement"
        - "Low - minor enhancement"
      default: 2
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to implement this feature
        - label: I can help with testing and validation
        - label: I can provide documentation
        - label: I can only provide feedback and requirements

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information, mockups, or references
      placeholder: |
        - Links to relevant documentation
        - Screenshots or mockups
        - Related projects or tools
        - Technical considerations
