{{- if and .Values.namespace.create .Values.namespace.name }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- include "kserve-vllm-mini.labels" . | nindent 4 }}
{{- end }}
