{{- $s3 := .Values.inferenceService.predictor.s3 -}}
{{- if and .Values.inferenceService.enabled $s3.createSecret (not (empty $s3.accessKeyId)) (not (empty $s3.secretAccessKey)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-s3" (include "kserve-vllm-mini.fullname" .)) $s3.secretName }}
  labels:
    {{- include "kserve-vllm-mini.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ $s3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ $s3.secretAccessKey | quote }}
  AWS_DEFAULT_REGION: {{ ($s3.region | default "us-east-1") | quote }}
{{- end }}
