name: Auto Format Shell Scripts

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.sh'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.sh'
  workflow_dispatch:

jobs:
  shfmt:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Install shfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y shfmt

      - name: Run shfmt (auto-fix)
        run: |
          set -e
          files=$(git ls-files '*.sh' || true)
          if [ -n "$files" ]; then
            shfmt -i 2 -bn -ci -w "$files"
          else
            echo "No shell files to format"
          fi

      - name: Detect changes
        id: diff
        run: |
          if git diff --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit changes directly (push events)
        if: github.event_name == 'push' && steps.diff.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: shfmt auto-format"
          file_pattern: "*.sh"

      - name: Create Pull Request with formatting (PR events)
        if: github.event_name == 'pull_request' && steps.diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "style: shfmt auto-format"
          title: "style: shfmt auto-format"
          body: "Automated shell formatting via shfmt."
          branch: "ci/shfmt-autoformat-${{ github.head_ref || github.ref_name }}"
          delete-branch: true
          add-paths: |
            **/*.sh
          labels: |
            automated
            formatting
