name: CI
on: [push, pull_request]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt && pip install -r requirements-dev.txt
      - name: Run lint and tests
        run: make lint && make test
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@v2
      - name: Upload Report
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-report
          path: runs/**/report.html
          if-no-files-found: ignore
