name: SLO Gate

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-and-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest pyyaml
      - name: Run unit tests
        run: pytest -q
      - name: Gate should PASS with good sample
        run: |
          ./tools/gate.py --results tests/data/results_good.json --energy tests/data/energy_good.json --slo slo.json
      - name: Gate should FAIL with bad sample
        run: |
          set +e
          ./tools/gate.py --results tests/data/results_bad.json --slo slo.json
          test $? -ne 0
